### ISSUE TITLE
Нужно было опубликовать на Github Pages

### ISSUE THREAD

**Issue by coursar** [VokkeRr/Purchase#1]

**Comment by VokkeRr** [comment]
bfbb69999f938bdaa20180f3a64b06000dea97e2  
issue is closed

**Comment by VokkeRr** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/59592285/73336996-6e305900-4284-11ea-9f48-b598f86eb957.png)

some problems appeared on server!
